# Generated by Django 2.2 on 2019-11-25 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newscenter', '0004_auto_20180104_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsroom',
            field=models.ForeignKey(blank=True, help_text='If set, this category will be associated with the newsroom', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newscenter.Newsroom'),
        ),
        migrations.AlterField(
            model_name='article',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='feeds',
            field=models.ManyToManyField(blank=True, help_text='Select all areas in which this article should be listed', related_name='articles', to='newscenter.Feed'),
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Primary location, appearing on the article detail page', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newscenter.Location'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Automatically generated from the title.', unique=True, unique_for_date='release_date', verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='teaser',
            field=models.TextField(blank=True, help_text='A summary preview of the article.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Automatically generated from the title.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, help_text='Text to be displayed below the image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Images larger than the configured dimensions will be resized', upload_to='newscenter_uploads'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='This will be used for the image alt text.', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.BooleanField(default=False, help_text='To be displayed on article listing pages. If more than one is selected, the thumbnail used will be chosen at random.', verbose_name='Use as Thumbnail'),
        ),
    ]
