# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-07-26 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newscenter', '0005_article_audio_file'),
        ('newscenter', '0004_auto_20180104_1119'),
    ]

    operations = [
    ]
