# Generated by Django 2.2 on 2019-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscenter', '0005_auto_20191125_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='If configured in templates, this image will display on the newsroom index', upload_to='newscenter_uploads'),
        ),
    ]
